### ISSUE TITLE
Dynamic recipients

### ISSUE THREAD

**Issue by chris-rs** [laravel-notification-channels/messagebird#12]
Great component that uses the new notification system, but I noticed the component does not use dynamic recipients. It just reads the recipients variable from the config file. 
This does not allow for sending notifications to notifiable models with a phone number.

**Comment by petericebear** [comment]
It is possible to set the recipients, I will make it dynamic from the model. Hope to fix it before this weekend

**Comment by chris-rs** [comment]
Great Peter, take your time! I will take a look when you’re ready.

Regards

From: Peter Steenbergen
Reply-To: laravel-notification-channels/messagebird
Date: Thursday, 6 October 2016 at 16:19
To: laravel-notification-channels/messagebird
Cc: Chris, Author
Subject: Re: [laravel-notification-channels/messagebird] Dynamic recipients (#12)

It is possible to set the recipients, I will make it dynamic from the model. Hope to fix it before this weekend

**Comment by petericebear** [comment]
I have committed the code, but need to add some documentation to it

**Comment by chris-rs** [comment]
Hi Peter,

Thanks, I will check it soon and let you know my findings.

Regards,
Chris

Op 10 okt. 2016 om 16:55 heeft Peter Steenbergen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

I have committed the code, but need to add some documentation to it

##

**Comment by evrard-c** [comment]
Is it now possible to use thi well done package for sending notifications to notifiable models with a phone number?
I tried to do it but without success

**Comment by frco9** [comment]
The code available on master is not published on composer, thus this package is still not working out of the box :/ 

Could you push the update to composer !? 

Thanks

**Comment by laemol** [comment]
If you pulled this in with Composer it should work like this
`return (new MessagebirdMessage("Your {$notifiable->service} was ordered!"))->setRecipients($recipients);`
Where` $recipients` can be an array with you phone numbers.

**Comment by petericebear** [comment]
Will update the version.

**Comment by laemol** [comment]
Thanks!
